[package]
name = "ios-storekit2-status"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "StoreKit 2 purchase ability status for iOS"
build = "build.rs"

[build-dependencies]
cc = "=1.6.0"

[lints]
workspace = true
